### ISSUE TITLE
space-hogs: Discover surprisingly large directories on the command line

### ISSUE THREAD

**Issue by dylang** [groupon/ndu#5]
Hi friends at Groupon! 

Thanks for creating this module.

I've created something similar recently called [space-hogs](https://github.com/dylang/space-hogs) that I thought you might be interested in. I probably created it for the same reason - to investigate what was making our dependency tree so large, especially when we `webpack`ed it for the web.

By default `space-hogs` shows the largest directories, and it chooses how big is "big enough" to show. For example:

```
$ space-hogs 
21 MB ~/projects/ndu
Directories larger than 2 MB
├──  4 MB [▒   ] /node_modules/lodash
├──  3 MB [▒   ] /node_modules/browserify/node_modules/crypto-browserify/node_modules
└── 13 MB [▒▒▒ ] (everything else)
    21 MB Total
```

You can also change the directory it uses and the threshold for displaying large directories:

```
$ space-hogs ./node_modules/ndu 1
21 MB ./node_modules/ndu
Directories larger than 1 MB
├──  1 MB [▒   ] /node_modules/d3/src
├──  1 MB [▒   ] /node_modules/lodash/fp
├──  2 MB [▒   ] /node_modules/browserify/test
├──  1 MB [▒   ] /node_modules/browserify/node_modules/browserify-zlib
├──  1 MB [▒   ] /node_modules/browserify/node_modules/module-deps
├──  2 MB [▒   ] /node_modules/browserify/node_modules/insert-module-globals/node_modules
├──  1 MB [▒   ] /node_modules/browserify/node_modules/crypto-browserify/node_modules/browserify-sign
└── 12 MB [▒▒▒ ] (everything else)
    21 MB Total
```

I think both our tools share a similar issue: `npm@3` does a flat install, so something like `browserify` might seem small even though it includes several MB from other modules.

Thanks again, and glad I'm not the only person wondering about the size of the modules. :smile:

**Comment by jkrems** [comment]
Thanks! Didn't know about `space-hogs`, looks neat! Might be a good idea to add a "similar tools" section to our README.

We're still sticking with `npm@2`, so I didn't even consider the effect of flat dependency trees. Good point. I want to make `ndu` a bit smarter about relations anyhow (e.g. make it aware of `devDependencies`), so it might be a good idea of correctly tracking deduped dependencies to attribute those appropriately.

**Comment by dylang** [comment]
Thanks! Good idea about "similar tools" section, I can do the same.

**Comment by dylang** [comment]
:heavy_check_mark: https://github.com/dylang/space-hogs#similar-tools

**Comment by dylang** [comment]
Thanks for the link!

> We're still sticking with npm@2

One way we shrunk our dependencies considerably was by moving to `npm@3`. For example: 

```
$ npm ls cipher-base
└─┬ ndu@1.1.2
  └─┬ browserify@13.0.0
    └─┬ crypto-browserify@3.11.0
      ├─┬ browserify-cipher@1.0.0
      │ ├─┬ browserify-aes@1.0.6
      │ │ └── cipher-base@1.0.2
      │ └─┬ browserify-des@1.0.0
      │   └── cipher-base@1.0.2
      ├─┬ browserify-sign@4.0.0
      │ └─┬ parse-asn1@5.0.0
      │   └─┬ browserify-aes@1.0.6
      │     └── cipher-base@1.0.2
      ├─┬ create-hash@1.1.2
      │ └── cipher-base@1.0.2
      └─┬ public-encrypt@4.0.0
        └─┬ parse-asn1@5.0.0
          └─┬ browserify-aes@1.0.6
            └── cipher-base@1.0.2
```
That's 5 copies with `npm@2`, only one copy with `npm@3`.

You can find the count of dups using [pkgcount](https://github.com/timoxley/pkgcount).
