### ISSUE TITLE
Document "du" requirement

### ISSUE THREAD

**Issue by ismyrnow** [groupon/ndu#7]
I just tried this on Windows, and found it didn't work, since it requires the `du` utility to run `du -k node_modules/*`.

Could you add that to the list of requirements (alongside Node v4)?

**Comment by InfiniteStyles** [comment]
Had the same problem. Is there a way to run this on windows?

**Comment by jkrems** [comment]
It's a fairly thin wrapper around `du`, so I'm afraid not. At least not without a considerable amount of work. It might work in the new `bash` mode but I didn't try yet.

**Comment by jkrems** [comment]
@ismyrnow Sorry for that, yes. We definitely should mention it in the README and possible even warn on install when used on Windows.
